site_name: GenJAXMix

theme:
  name: "material"

plugins:
  - mkdocs-jupyter:
      execute: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false


nav: 
  - Home: index.md
  - Tutorials: 
    - Getting Started: tutorials/getting_started.py
    - DPMMs from the Ground Up: tutorials/dpmm_ground_up.ipynb
    - Splitting Clusters: tutorials/sub_cluster.ipynb
  - Library Reference: 
    - API: reference/api.md
    - Conjugacy: reference/conjugacy.md
    - Inference: reference/inference.md
  - For Developers: dev.md